"""
real.launch.py — full weed-detection pipeline on physical UR5 + RealSense D435.

No Gazebo, no HSV stubs, no field_manager. YOLO-only detection.

Usage:
    ros2 launch real_simulation_ur5 real.launch.py robot_ip:=192.168.1.113
    ros2 launch real_simulation_ur5 real.launch.py robot_ip:=192.168.1.113 dry_run:=false
    ros2 launch real_simulation_ur5 real.launch.py robot_ip:=192.168.1.113 model_path:=/path/to/best.pt

Before running:
    1. Fill in config/camera_params.yaml (from easy_handeye2 or manual measurement).
    2. Ensure ~/ur5_calibration.yaml exists (generated by ros2 run ur_calibration ...).
    3. Place best.pt at /home/lior/best.pt or pass model_path:= at launch.
    4. Start with dry_run:=true (default) — arm scans and centres but never fires.
"""

import os
import yaml
from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument, TimerAction
from launch.substitutions import LaunchConfiguration
from launch_ros.actions import Node
from ament_index_python.packages import get_package_share_directory
from launch.launch_description_sources import PythonLaunchDescriptionSource
from launch.actions import IncludeLaunchDescription
from launch.substitutions import PathJoinSubstitution
from launch_ros.substitutions import FindPackageShare

DEFAULT_ROBOT_IP = '192.168.1.113'

# Load camera mount geometry at module level so the static TF args are
# available as Python values (same pattern as watermelon_demo/demo_real.launch.py).
_pkg_src = os.path.dirname(__file__)
_cam_cfg_path = os.path.join(_pkg_src, '..', 'config', 'camera_params.yaml')
try:
    with open(_cam_cfg_path) as _f:
        _cam_cfg = yaml.safe_load(_f)
    _cam = _cam_cfg['mount']
except (FileNotFoundError, KeyError) as _exc:
    raise RuntimeError(
        f'Cannot read camera_params.yaml ({_exc}). '
        'Fill in real_simulation_ur5/config/camera_params.yaml before launching.'
    ) from _exc

_calibrated = bool(_cam_cfg.get('calibrated', False))
if _calibrated:
    _rotation_args = [
        '--qx', str(float(_cam['qx'])),
        '--qy', str(float(_cam['qy'])),
        '--qz', str(float(_cam['qz'])),
        '--qw', str(float(_cam['qw'])),
    ]
else:
    _rotation_args = [
        '--roll',  str(float(_cam['roll'])),
        '--pitch', str(float(_cam['pitch'])),
        '--yaw',   str(float(_cam['yaw'])),
    ]


def generate_launch_description():
    pkg = get_package_share_directory('real_simulation_ur5')
    params_file = os.path.join(pkg, 'config', 'real_params.yaml')

    robot_ip_arg = DeclareLaunchArgument(
        'robot_ip', default_value=DEFAULT_ROBOT_IP,
        description='IP address of the UR5 controller')

    dry_run_arg = DeclareLaunchArgument(
        'dry_run', default_value='true',
        description='true = scan+centre only (no laser fire); false = full pipeline')

    model_path_arg = DeclareLaunchArgument(
        'model_path', default_value='/home/lior/best.pt',
        description='Path to YOLO .pt weights file')

    robot_ip   = LaunchConfiguration('robot_ip')
    dry_run    = LaunchConfiguration('dry_run')
    model_path = LaunchConfiguration('model_path')

    # 1. UR5 driver — robot_state_publisher, joint_state_broadcaster,
    #    scaled_joint_trajectory_controller
    ur_driver = IncludeLaunchDescription(
        PythonLaunchDescriptionSource(
            PathJoinSubstitution([
                FindPackageShare('ur_robot_driver'),
                'launch', 'ur_control.launch.py',
            ])
        ),
        launch_arguments={
            'ur_type':                'ur5',
            'robot_ip':               robot_ip,
            'launch_rviz':            'false',
            'kinematics_params_file': os.path.expanduser('~/ur5_calibration.yaml'),
        }.items(),
    )

    # 2. RealSense D435 — colour stream only, topic: /camera/color/image_raw
    realsense = Node(
        package='realsense2_camera',
        executable='realsense2_camera_node',
        name='realsense2_camera',
        parameters=[{
            'enable_color': True,
            'enable_depth': False,
            'color_width': 640,
            'color_height': 480,
            'color_fps': 30.0,
        }],
        output='screen',
    )

    # 3. Static TF: tool0 → camera_link (from camera_params.yaml)
    camera_tf = Node(
        package='tf2_ros',
        executable='static_transform_publisher',
        name='camera_tf',
        arguments=[
            '--x', str(float(_cam['x'])),
            '--y', str(float(_cam['y'])),
            '--z', str(float(_cam['z'])),
            *_rotation_args,
            '--frame-id',       'tool0',
            '--child-frame-id', 'camera_link',
        ],
    )

    # 4. Static TF: tool0 → laser_link (co-mounted with camera)
    laser_tf = Node(
        package='tf2_ros',
        executable='static_transform_publisher',
        name='laser_tf',
        arguments=[
            '--x', str(float(_cam['x'])),
            '--y', str(float(_cam['y'])),
            '--z', str(float(_cam['z'])),
            *_rotation_args,
            '--frame-id',       'tool0',
            '--child-frame-id', 'laser_link',
        ],
    )

    # 5. Demo nodes — delayed 15 s so UR driver and controllers are fully up
    demo_nodes = TimerAction(period=15.0, actions=[
        Node(
            package='real_simulation_ur5',
            executable='detection_node',
            name='detection_node',
            parameters=[params_file, {'model_path': model_path}],
            output='screen',
        ),
        Node(
            package='real_simulation_ur5',
            executable='arm_controller_node',
            name='arm_controller_node',
            parameters=[params_file, {'dry_run': dry_run}],
            output='screen',
        ),
        Node(
            package='real_simulation_ur5',
            executable='laser_effect_node',
            name='laser_effect_node',
            parameters=[params_file],
            output='screen',
        ),
        Node(
            package='rqt_image_view',
            executable='rqt_image_view',
            name='detection_display',
            arguments=['/detection_image'],
            output='log',
        ),
        Node(
            package='rviz2',
            executable='rviz2',
            name='rviz2',
            arguments=['-d', os.path.join(
                get_package_share_directory('watermelon_demo'),
                'config', 'ur5_camera_basic.rviz')],
            output='log',
        ),
    ])

    return LaunchDescription([
        robot_ip_arg,
        dry_run_arg,
        model_path_arg,
        ur_driver,
        realsense,
        camera_tf,
        laser_tf,
        demo_nodes,
    ])
